#  ____  __  __ ______
# |  _ \|  \/  |  ____|
# | |_) | \  / | |__
# |  _ <| |\/| |  __|
# | |_) | |  | | |____
# |____/|_|  |_|______|
#
# Made for Blockminer by SleazLee and AI Assistant.

serverName: "blockminer"

#The start of a list of Systems.
Systems:

  Discord:
    # link to the discord
    Link: "https://discord.gg/NGx7DzFZAE"

  # Enables the /tpshop <###> command.
  TPShop:
    Enabled: true

  # Enables the vote system that listens for votes.
  VoteSystem:
    Enabled: true

    # Change the sound that plays when a player votes. (Default: ENTITY_EXPERIENCE_ORB_PICKUP)
    Sounds: "ENTITY_EXPERIENCE_ORB_PICKUP"

    Particles:
      # Sets the particle radius around the player. (Default: 6)
      Radius: 6

  # Enables the wild teleport system.
  Wild:
    Enabled: true
    Center:
      X: 256
      Z: 256
    Bounds:
      1:
        Version: 1.19
        Lower: 256
        Upper: 19711
      2:
        Version: 1.21
        Lower: 20224
        Upper: 29439
      3:
        Version: 1.21.4
        Lower: 29952
        Upper: 39167

      # Add new versions as needed
      # 3:
      #   Version: <version>
      #     [Hint] Region max cords -256 for lower and upper.
      #   Lower: <value>
      #   Upper: <value>

    Regions:
      1:
        Name: "ranks"
        Return: "ranks"
      2:
        Name: "shop1"
        Return: "shops"
      3:
        Name: "shop2"
        Return: "shops"
      4:
        Name: "shop3"
        Return: "shops"
      5:
        Name: "shop4"
        Return: "shops"
      6:
        Name: "rules"
        Return: "rules"
      7:
        Name: "guidelines"
        Return: "guidelines"
      8:
        Name: "voteshop"
        Return: "voteshop"
      9:
        Name: "healingsprings"
        Return: "healingsprings"
      10:
        Name: "obelisk"
        Return: "obelisk"
      11:
        Name: "wishingwell"
        Return: "wishingwell"
      12:
        Name: "platform"
        Return: "platform"
      13:
        Name: "theeventportal"
        Return: "theeventportal"
      14:
        Name: "spawn"
        Return: "spawn"

      # Add new regions as needed
      # 3:
      #   Name: <Region Name>
      #   Return: <Return Value>

  # Enables spawn only systems.
  SpawnSystems:
    Enabled: true

    McmmoBoost:
      # Chance to get a McMMO Boost at all. (Default 0.33, this means 33% chance)
      TotalChance: 0.33
      # These should all add up to 1.00.
      # Default 0.43
      TenPercentChance: 0.43
      # Default 0.25
      FiftyPercentChance: 0.25
      # Default 0.19
      OneHundredFiftyPercentChance: 0.19
      # Default 0.13
      TwoHundredPercentChance: 0.13

    DiamondCatch:
      # Chance to get free Diamonds from the Wishing-Well. (Default 0.50, this means 50% chance)
      TotalChance: 0.50
      # These should all add up to 1.00.
      # Default 0.06
      TenToFifty: 0.06
      # Default 0.18
      ThreeToTen: 0.18
      # Default 0.32
      OneToThree: 0.32
      # Default 0.44
      One: 0.44

    Altars:
      HealingSprings:
        x: 201
        y: 61
        z: 164
        direction: WEST
      WishingWell:
        x: 210
        y: 71
        z: 309
        direction: NORTH
      Obelisk:
        x: 323
        y: 71
        z: 288
        direction: EAST

  # Enables all the common commands.
  CommonCommands:
    Enabled: true

  # Enables the trash system.
  Containers:
    Enabled: true

  # Enables the Velocity Tell system.
  VTell:
    Enabled: true

  # Enables the Map system.
  Maps:
    Enabled: true

    # Map links
    Default: "https://blockminer.net/map/"

  # Enables the Ban/Mute system.
  Punishments:
    Enabled: true

  # Enables the Donation system.
  Donations:
    Enabled: true

  # Enables the Trophies system.
  Trophies:
    Enabled: true

  # Enables the vot time/weather system.
  Vot:
    Enabled: true
    VoteDurationSeconds: 60
    CooldownMinutes: 15
    BookLayouts:
      NewVote:
        - '<dark_gray><st>                            </st><newline><bold>         <gold>Vot</bold><newline><dark_gray><st>                            </st><newline><#594e44>Time:<newline><bold>         <click:run_command:/vot day><hover:show_text:"<#ffd746>Click to start vote for Day Time"><#ffd746>Day</hover></click><newline>        <click:run_command:/vot night><hover:show_text:"<gray>Click to start vote for Night Time"><#1e1e43>Night</hover></click><newline></bold><newline><#594e44>Weather:<newline><bold><newline>        <click:run_command:/vot clear><hover:show_text:"<#63a1f2>Click to start vote for Clear Weather"><#63a1f2>Clear</hover></click><newline>        <click:run_command:/vot rain><hover:show_text:"<#4e4dce>Click to start vote for Rainy Weather"><#4e4dce>Rainy</hover></click><newline>   <click:run_command:/vot thunder><hover:show_text:"<#6d5091>Click to start vote for a Thunderstorm"><#6d5091>Thunderstorm</hover></click><newline></bold><newline><dark_gray><st>                            </st>'

      CurrentVote:
        - '<dark_gray><st>                            </st><newline>            <gold><bold>Vot</bold><newline><dark_gray><st>                            </st><newline><newline><dark_gray>    Would you like to<newline>    <dark_gray>vote for {color}<bold>{vote_type}</bold><dark_gray>?<newline><newline><newline>            <click:run_command:/vot yes><hover:show_text:"<green>Click to vote Yes"><green><bold>Yes</bold></hover></click><newline><newline><newline>             <click:run_command:/vot no><hover:show_text:"<red>Click to vote No"><red><bold>No</bold></hover></click><newline><newline><dark_gray><st>                            </st>'

      CooldownActive:
        - '<dark_gray><st>                            </st><newline><bold>         <#ff3300>Vot</bold><newline><dark_gray><st>                            </st><newline><dark_gray><newline><newline>   You have to wait      <newline>    <red><bold>{time_left}</bold><dark_gray> before<newline><newline>    you can start a<newline><newline>        new vote!<newline><newline><dark_gray><st>                            </st>'

  # Enables the Rankup System
  Rankup:
    Enabled: true

  # Enables the Migrator System
  Migrator:
    Enabled: false

  # Enables the Command Queue System
  CommandQueue:
    Enabled: true

  # The Help Menu Systems
  Help:
      Enabled: true

  # Enables the PlayerData Systems
  PlayerData:
    Enabled: true

    # Enables the Economy Systems
    EconomySystems:
      Enabled: true

  # Enables all Purpur feature Systems
  PurpurFeatures:
    Enabled: true