#  ____  __  __ ______
# |  _ \|  \/  |  ____|
# | |_) | \  / | |__
# |  _ <| |\/| |  __|
# | |_) | |  | | |____
# |____/|_|  |_|______|
#
# Made for Blockminer by SleazLee and AI Assistant.

serverName: "blockminer"

#The start of a list of Systems.
Systems:

  Discord:
    # link to the discord
    Link: "https://discord.gg/NGx7DzFZAE"

  # Enables the /tpshop <###> command.
  TPShop:
    Enabled: true

  # Enables the vote system that listens for votes.
  VoteSystem:
    Enabled: true

    # Change the sound that plays when a player votes. (Default: ENTITY_EXPERIENCE_ORB_PICKUP)
    Sounds: "ENTITY_EXPERIENCE_ORB_PICKUP"

    Particles:
      # Sets the particle radius around the player. (Default: 6)
      Radius: 6

  # Enables the wild teleport system.
  Wild:
    Enabled: true
    Center:
      X: 256
      Z: 256
    Bounds:
      1:
        Version: 1.19
        Lower: 256
        Upper: 19711
      2:
        Version: 1.21
        Lower: 20224
        Upper: 29439
      3:
        Version: 1.21.5
        Lower: 29952
        Upper: 39167

      # Add new versions as needed
      # 3:
      #   Version: <version>
      #     [Hint] Region max cords -256 for lower and upper.
      #   Lower: <value>
      #   Upper: <value>

    Regions:
      1:
        Name: "ranks"
        Return: "ranks"
      2:
        Name: "shop1"
        Return: "shops"
      3:
        Name: "shop2"
        Return: "shops"
      4:
        Name: "shop3"
        Return: "shops"
      5:
        Name: "shop4"
        Return: "shops"
      6:
        Name: "rules"
        Return: "rules"
      7:
        Name: "guidelines"
        Return: "guidelines"
      8:
        Name: "voteshop"
        Return: "voteshop"
      9:
        Name: "healingsprings"
        Return: "healingsprings"
      10:
        Name: "obelisk"
        Return: "obelisk"
      11:
        Name: "wishingwell"
        Return: "wishingwell"
      12:
        Name: "platform"
        Return: "platform"
      13:
        Name: "theeventportal"
        Return: "theeventportal"
      14:
        Name: "spawn"
        Return: "spawn"

      # Add new regions as needed
      # 3:
      #   Name: <Region Name>
      #   Return: <Return Value>

  # Enables the SimplePortals system.
  SimplePortals:
    Enabled: true

  # Enables spawn only systems.
  SpawnSystems:
    Enabled: true

    McmmoBoost:
      # Chance to get a McMMO Boost at all. (Default 0.33, this means 33% chance)
      TotalChance: 0.33
      # These should all add up to 1.00.
      # Default 0.43
      TenPercentChance: 0.43
      # Default 0.25
      FiftyPercentChance: 0.25
      # Default 0.19
      OneHundredFiftyPercentChance: 0.19
      # Default 0.13
      TwoHundredPercentChance: 0.13

    DiamondCatch:
      # Chance to get free Diamonds from the Wishing-Well. (Default 0.50, this means 50% chance)
      TotalChance: 0.50
      # These should all add up to 1.00.
      # Default 0.06
      TenToFifty: 0.06
      # Default 0.18
      ThreeToTen: 0.18
      # Default 0.32
      OneToThree: 0.32
      # Default 0.44
      One: 0.44

    Altars:
      HealingSprings:
        x: 201
        y: 61
        z: 164
        direction: WEST
      WishingWell:
        x: 210
        y: 71
        z: 309
        direction: NORTH
      Obelisk:
        x: 323
        y: 71
        z: 288
        direction: EAST

  # Enables all the common commands.
  CommonCommands:
    Enabled: true

  # Enables the trash system.
  Containers:
    Enabled: true

  # Enables the Velocity Tell system.
  VTell:
    Enabled: true

  # Enables the Map system.
  Maps:
    Enabled: true

    # Map links
    Default: "https://blockminer.net/map/"

  # Enables the Ban/Mute system.
  Punishments:
    Enabled: true

  # Enables the Donation system.
  Donations:
    Enabled: true

  # Enables the Trophies system.
  Trophies:
    Enabled: true

  # Enables the vot time/weather system.
  Vot:
    Enabled: true
    VoteDurationSeconds: 60
    CooldownMinutes: 15
    BookLayouts:
      NewVote:
        - '<dark_gray><st>                            </st><newline><bold>         <gold>Vot</bold><newline><dark_gray><st>                            </st><newline><#594e44>Time:<newline><bold>         <click:run_command:/vot day><hover:show_text:"<#ffd746>Click to start vote for Day Time"><#ffd746>Day</hover></click><newline>        <click:run_command:/vot night><hover:show_text:"<gray>Click to start vote for Night Time"><#1e1e43>Night</hover></click><newline></bold><newline><#594e44>Weather:<newline><bold><newline>        <click:run_command:/vot clear><hover:show_text:"<#63a1f2>Click to start vote for Clear Weather"><#63a1f2>Clear</hover></click><newline>        <click:run_command:/vot rain><hover:show_text:"<#4e4dce>Click to start vote for Rainy Weather"><#4e4dce>Rainy</hover></click><newline>   <click:run_command:/vot thunder><hover:show_text:"<#6d5091>Click to start vote for a Thunderstorm"><#6d5091>Thunderstorm</hover></click><newline></bold><newline><dark_gray><st>                            </st>'

      CurrentVote:
        - '<dark_gray><st>                            </st><newline>            <gold><bold>Vot</bold><newline><dark_gray><st>                            </st><newline><newline><dark_gray>    Would you like to<newline>    <dark_gray>vote for {color}<bold>{vote_type}</bold><dark_gray>?<newline><newline><newline>            <click:run_command:/vot yes><hover:show_text:"<green>Click to vote Yes"><green><bold>Yes</bold></hover></click><newline><newline><newline>             <click:run_command:/vot no><hover:show_text:"<red>Click to vote No"><red><bold>No</bold></hover></click><newline><newline><dark_gray><st>                            </st>'

      CooldownActive:
        - '<dark_gray><st>                            </st><newline><bold>         <#ff3300>Vot</bold><newline><dark_gray><st>                            </st><newline><dark_gray><newline><newline>   You have to wait      <newline>    <red><bold>{time_left}</bold><dark_gray> before<newline><newline>    you can start a<newline><newline>        new vote!<newline><newline><dark_gray><st>                            </st>'

  # Enables the Rankup System
  Rankup:
    Enabled: true

  # Enables the Migrator System
  Migrator:
    Enabled: false

  # Enables the Command Queue System
  CommandQueue:
    Enabled: true

  # The Help Menu Systems
  Help:
      Enabled: true

  # Enables the PlayerData Systems
  PlayerData:
    Enabled: true

    # Enables the Economy Systems
    EconomySystems:
      Enabled: true

  # Enables all Purpur feature Systems
  PurpurFeatures:
    Enabled: true

  # Enables the afk system
  AFKSystem:
    Enabled: true

  # Enables the Lands TP Fix System
  LandsTPFix:
    Enabled: true

  Shops:
    Enabled: true
    Messages:
      players-only: '<red>Only players can use this command.</red>'
      usage: '<red>Usage: /bms <buy|disband|invite|remove|transfer|leave|accept|decline|extend|name|tp></red>'
      buy-usage: '<red>/bms buy <shop></red>'
      invite-usage: '<red>/bms invite <player></red>'
      remove-usage: '<red>/bms remove <player></red>'
      transfer-usage: '<red>/bms transfer <player></red>'
      name-set-usage: '<red>/bms name set <name></red>'
      unknown-command: '<red>Unknown command.</red><white> Need help with commands? Check out </white><click:run_command:"/help"><hover:show_text:"<gold>Click to run /help</gold>"><gold>/help</gold></hover></click><white>.</white>'
      not-in-shop: '<red>Stand inside the shop plot you’d like to buy and try again.</red>'
      shop-already-rented: '<red>Sorry but this shop is already Owned!</red>'
      already-manage: '<red>You can only own one shop at a time!</red>'
      cannot-afford-shop: '<red>You don’t have enough money to purchase this shop.</red>'
      shop-rented: '<green>You just purchased your very own shop! Give it a name with /bms name</green>'
      not-owner: '<red>You do not yet own a shop. Click a shops sign to purchase it.</red>'
      disband-confirm: '<red>Are you sure you want to do this? Type /bms disband confirm to confirm.</red>'
      shop-disbanded: '<green>You’ve successfully disbanded your shop.</green>'
      player-not-found: '<red>That player cannot be found!<gray> Try again.</red>'
      player-already-manages: '<red>That player already owns a shop.</red>'
      coowner-added: '<green><bold>{player}</bold> has been added as co-owner!</green>'
      you-are-coowner: '<green>You are now co-owner of shop {id}.</green>'
      coowner-removed: '<green><bold>{player}</bold> is no longer a co-owner!</green>'
      you-are-not-coowner: '<red>You are no longer co-owner of shop #{id}.</red>'
      no-coowner: '<red>You have no co-owner to transfer to.</red>'
      not-your-coowner: '<red>That player is not your co-owner.</red>'
      ownership-transferred: '<green>You’ve successfully transferred Ownership of your shop.</green>'
      you-now-own: '<green>Congratulations you are the new owner of shop #{id}.</green>'
      not-manage: '<red>You do not currently own a shop!<gray> Purchase one and try again.</red>'
      beyond-max: '<red>Cannot extend beyond maximum time.</red>'
      cannot-afford-rent: '<red>You don’t have enough money to extend your shops rent.</red>'
      rent-extended: '<green>You’ve extended your shops rent!</green>'
      name-too-long: '<red>That name is too long.<gray> Names must be under <green>15<gray> characters.'
      shop-renamed: '<green>You’ve succesffully named your Shop!</green>'
      shop-not-found: '<red>That Shop could not be found! <gray>Try again.</red>'
      admin-no-permission: '<red>Unknown command.</red><white> Need help with commands? Check out </white><click:run_command:"/help"><hover:show_text:"<gold>Click to run /help</gold>"><gold>/help</gold></hover></click><white>.</white>'
      admin-usage: '<red>Usage: /bms admin <renewall|disband></red>'
      admin-renewall: '<green>You’ve extended the time on all the shops!</green>'
      admin-disband-usage: '<red>/bms admin disband <region> [confirm]</red>'
      admin-disband-confirm: '<red>Type /bms admin disband {region} confirm to disband.</red>'
      admin-disbanded: '<green>Region {region} disbanded.</green>'
      name-usage: '<red>Usage: /bms name <set|color|hex> <value></red>'
      color-changed: '<green>You’ve updated your shops sign color!</green>'
      color-no-permission: '<red>You must have the donor rank Plus or above to color your shop name!</red>'
      hex-no-permission: '<red>You must have the donor rank Super or above to use hex codes!</red>'
      invalid-color: '<red>That color is not on the list, try again.</red>'
      invalid-hex: '<red>That is an Invalid hex color.<gray> Try: <#55FF55>#55ff55</red>'
      tp-set-success: '<green>You’ve updated your shops tp location!</green>'
      tp-too-far: '<red>You Can only set your shops teleport up to 9 blocks away!</red>'
      invite-sent: '<green>You sent a request asking {player} if they’d like to Co-Own your shop.</green>'
      invite-expired: '<red>You do not have a pending shop invite!</red>'
      invite-declined: '<red><bold>{player}</bold> has declined your invite.</red>'
      invite-declined-you: '<red>You declined {sender}’s shop invite.</red>'
      leave-confirm: '<red>Are you sure you want to do this? <gray> Type <aqua>/bms leave confirm to confirm.</gray>'
      left-shop: '<green>You are no longer a Co-Owner of shop {id}.</green>'
      leave-owner: '<red>You cannot do this!<gray> Use <aqua>/bms disband instead.</gray>'

