#  ____  __  __ ______
# |  _ \|  \/  |  ____|
# | |_) | \  / | |__
# |  _ <| |\/| |  __|
# | |_) | |  | | |____
# |____/|_|  |_|______|
#
# Made for Blockminer by SleazLee and AI Assistant.

serverName: "blockminer"

MySQL:
  host: Host
  port: Port
  user: Username
  password: Password
  database: DatabaseName

#The start of a list of Systems.
systems:


  discord:
    # link to the discord
    link: "https://discord.gg/NGx7DzFZAE"

  # Enables the /tpshop <###> command.
  tpshop:
    enabled: true

  # Enables the vote system that listens for votes.
  votesystem:
    enabled: true

    # Change the sound that plays when a player votes. (Default: ENTITY_EXPERIENCE_ORB_PICKUP)
    sounds: "ENTITY_EXPERIENCE_ORB_PICKUP"

    particles:
      # Sets the particle radius around the player. (Default: 6)
      radius: 6

  # Enables the wild teleport system.
  bmwild:
    enabled: true

  # Enables spawn only systems.  (Default: false)
  spawnsystems:
    enabled: false

    mcmmoboost:
      # Chance to get a McMMO Boost at all. (Default 0.33, this means 33% chance)
      totalchance: 0.33
      # These should all add up to 1.00.
      # Default 0.43
      tenpercentchance: 0.43
      # Default 0.25
      fiftypercentchance: 0.25
      # Default 0.19
      onehundredfiftypercentchance: 0.19
      # Default 0.13
      twoHundredPercentChance: 0.13

    diamondcatch:
      # Chance to get free Diamonds from the Wishing-Well. (Default 0.50, this means 50% chance)
      totalchance: 0.50
      # These should all add up to 1.00.
      # Default 0.06
      tentofifty: 0.06
      # Default 0.18
      threetoten: 0.18
      # Default 0.32
      onetothree: 0.32
      # Default 0.44
      one: 0.44

    altars:
      healingsprings:
        x: -247
        y: 61
        z: -108
        direction: WEST
      wishingwell:
        x: -238
        y: 71
        z: 37
        direction: NORTH
      obelisk:
        x: -125
        y: 71
        z: 16
        direction: EAST

  # Enables all the common commands.
  commoncommands:
    enabled: true

  # Enables the trash system.
  containers:
    enabled: true

  # Enables the bungeetell system.
  bungeetell:
    enabled: true

  # Enables the Map system.
  maps:
    enabled: true

    # Map links
    default: "https://blockminer.net/map/spawn"

  # Enables the Ban/Mute system.
  punishments:
    enabled: true

  # Enables the Donation system.
  donations:
    enabled: true

  # Enables the Trophies system.
  trophies:
    enabled: true