name: BMEssentials
version: 2.0
api-version: '1.21'
main: at.sleazlee.bmessentials.BMEssentials
author: SleazLee
description: One plugin to rule them all!
folia-supported: true

loadbefore: [Lands]
depend: [Vault]
softdepend: [HuskHomes, PlaceholderAPI]

commands:
  bme:
    description: Reloads the BMEssentials plugin.
    usage: /bme

  tpshop:
    description: Sends the player to a shop of their choosing.
    usage: /tpshop <###>

  wild:
    description: Teleports the player to a random server with a random world.
    usage: /wild

  rtp:
    description: Teleports the player to a random server with a random world.
    usage: /rtp

  randomtp:
    description: Teleports the player to a random server with a random world.
    usage: /randomtp

  randomteleport:
    description: Teleports the player to a random server with a random world.
    usage: /randomteleport

  firstjoinmessage:
    description: Sends repeating action bar messages to the player.
    usage: /firstjoinmessage

  trash:
    description: Opens a trash chest.
    usage: /trash
    aliases:
      - disposal

  craft:
    description: Open crafting table GUI
    usage: /craft
    permission: bm.containers.craft
    aliases:
      - crafting
      - craftingtable
      - workbench

  enderchest:
    description: Open a player enderchest GUI
    usage: /enderchest
    permission: bm.containers.enderchest
    aliases:
      - ec
      - echest

  cartography:
    description: Opens a cartography GUI
    usage: /cartography
    permission: bm.containers.cartography
    aliases:
      - cartographytable

  loom:
    description: Opens a loom GUI
    usage: /loom
    permission: bm.containers.loom

  stonecutter:
    description: Opens a stonecutter GUI
    usage: /stonecutter
    permission: bm.containers.stonecutter

  smithing:
    description: Opens a smithing GUI
    usage: /smithing
    permission: bm.containers.smithing
    aliases:
      - smithingtable
      - smith

  grindstone:
    description: Opens a grindstone GUI
    usage: /grindstone
    permission: bm.containers.grindstone
    aliases:
      - grstone
      - gstone

  anvil:
    description: Opens a anvil GUI
    usage: /anvil
    permission: bm.containers.anvil
    aliases:
      - openanvil
      - anv

  bungeetell:
    description: Sends a message to all players on the network.
    usage: /bungeetell

  adminvote:
    description: Sends a testvote to the player given.
    usage: /adminvote <player>

  map:
    description: Sends the player a link to the server map.
    usage: /map

  maps:
    description: Sends the player a link to the server map.
    usage: /maps

  springsheal:
    description: Heals the player.
    usage: /springsheal

  playtime:
    description: Shows the player their current Playtime.
    usage: /playtime

  lag:
    description: Displays general performance info.
    usage: /lag

  bmdiscord:
    description: Gives the player a discord link.
    usage: /bmdiscord

  mcmmoboost:
    description: gives a mcmmo boost to a player.
    usage: /mcmmobonus <player>

  diamondcatch:
    description: gives a random ammount of diamonds to a player.
    usage: /diamondcatch <player>

  autoban:
    description: Bans the player for hacking.
    usage: /autoban <player>

  unmute:
    description: Unmutes a player.
    usage: /unmute <player>

  donation:
    description: Give a selected player the selected donation package.
    usage: /donation <player> <package>

  trophyroom:
    aliases: [trophies, trophy]
    description: Opens a players Trophy Room.
    usage: /trophyroom <player>

  vot:
    description: Initiates a vote or casts a vote for changing time or weather.
    usage: /vot <day|night|clear|rain|thunder|yes|no|reset>
    aliases: [ vote ]
    permission: bmessentials.vot.use
    permission-message: '&cYou do not have permission to use this command.'

  adminvot:
    description: Allows admins to initiate a vote without cooldown.
    usage: /adminvot <day|night|clear|rain|thunder>
    permission: bmessentials.adminvot
    permission-message: You do not have permission to use this command.

  rankup:
    description: Rank up to the next level if conditions are met.
    usage: /rankup
    permission: rankup.use
    permission-message: You do not have permission to perform this command.

  migrateinventories:
    description: Migrates player inventories.
    usage: /migrateinventories
    permission: inventorymigrator.admin

  resetmigration:
    description: Resets the migration database.
    usage: /resetmigration
    permission: inventorymigrator.admin

  retrieveinventory:
    description: Retrieves your migrated inventory.
    usage: /retrieveinventory
    permission: inventorymigrator.retrieve

  commandqueue:
    description: Runs the command queue
    usage: /commandqueue run <player/console>

  book:
    description: Opens a help book.
    usage: /book <bookName>

  bookreload:
    description: Reloads the help books.
    usage: /bookreload
    permission: bmessentials.book.reload




permissions:
  bmessentials.vot.use:
    description: Allows the player to use the /vot command to start and participate in votes.
    default: true

  bmessentials.vot.reset:
     description: Allows the player to reset or finalize an ongoing vote using /vot reset.
     default: op

  bmessentials.vot.bypasscooldown:
     description: Allows the player to bypass the vote initiation cooldown.
     default: op

  rankup.use:
    description: Allows the user to attempt to rank up.
    default: true

  inventorymigrator.admin:
    description: Allows execution of admin commands.
    default: op

  inventorymigrator.retrieve:
    description: Allows players to retrieve their migrated inventory.
    default: true