name: BMEssentials
version: 2.0
api-version: '1.21'
main: at.sleazlee.bmessentials.BMEssentials
author: SleazLee
description: One plugin to rule them all!
folia-supported: true

loadbefore: [Lands, ChestSort, ChestSort-Folia]
depend: [WorldGuard, WorldEdit, mcMMO]
softdepend: [VaultUnlocked, HuskHomes, PlaceholderAPI, LuckPerms, Lands, BlueMap, QuickShop-Hikari]

commands:
  bme:
    description: Reloads the BMEssentials plugin.
    usage: /bme

  tpshop:
    description: Sends the player to a shop of their choosing.
    usage: /tpshop <shop>

  wild:
    description: Teleport to a random location or manage pregenerated spots.
    usage: /wild [version|admin]
    aliases:
    - rtp
    - randomtp
    - randomteleport

  firstjoinmessage:
    description: Sends repeating action bar messages to the player.
    usage: /firstjoinmessage

  trash:
    description: Opens a trash chest.
    usage: /trash
    aliases:
      - disposal

  craft:
    description: Open crafting table GUI
    usage: /craft
    permission: bm.containers.craft
    aliases:
      - crafting
      - craftingtable
      - workbench

  enderchest:
    description: Open a player enderchest GUI
    usage: /enderchest
    permission: bm.containers.enderchest
    aliases:
      - ec
      - echest

  cartography:
    description: Opens a cartography GUI
    usage: /cartography
    permission: bm.containers.cartography
    aliases:
      - cartographytable

  loom:
    description: Opens a loom GUI
    usage: /loom
    permission: bm.containers.loom

  stonecutter:
    description: Opens a stonecutter GUI
    usage: /stonecutter
    permission: bm.containers.stonecutter

  smithing:
    description: Opens a smithing GUI
    usage: /smithing
    permission: bm.containers.smithing
    aliases:
      - smithingtable
      - smith

  grindstone:
    description: Opens a grindstone GUI
    usage: /grindstone
    permission: bm.containers.grindstone
    aliases:
      - grstone
      - gstone

  anvil:
    description: Opens a anvil GUI
    usage: /anvil
    permission: bm.containers.anvil
    aliases:
      - openanvil
      - anv

  vtell:
    description: Sends a message to all players on the network.
    usage: /vtell

  adminvote:
    description: Sends a testvote to the player given.
    usage: /adminvote <player>

  map:
    description: Toggle your BlueMap visibility
    usage: /map <toggle|show|hide>

  maps:
    description: Toggle your BlueMap visibility
    usage: /maps <toggle|show|hide>



  playtime:
    description: Shows the player their current Playtime.
    usage: /playtime

  lag:
    description: Displays general performance info.
    usage: /lag

  bmdiscord:
    description: Gives the player a discord link.
    usage: /bmdiscord

  autoban:
    description: Bans the player for hacking.
    usage: /autoban <player>

  unmute:
    description: Unmutes a player.
    usage: /unmute <player>

  donation:
    description: Give a selected player the selected donation package.
    usage: /donation <player> <package>

  trophyroom:
    aliases: [trophies, trophy]
    description: Opens a players Trophy Room.
    usage: /trophyroom <player>

  vot:
    description: Initiates a vote or casts a vote for changing time or weather.
    usage: /vot <day|night|clear|rain|thunder|yes|no|reset>
    permission: bmessentials.vot.use
    permission-message: '&cYou do not have permission to use this command.'

  v:
    description: Initiates a vote or casts a vote for changing time or weather.
    usage: /v <day|night|clear|rain|thunder|yes|no|reset>
    permission: bmessentials.vot.use
    permission-message: '&cYou do not have permission to use this command.'

  adminvot:
    description: Allows admins to initiate a vote without cooldown.
    usage: /adminvot <day|night|clear|rain|thunder>
    permission: bmessentials.adminvot
    permission-message: You do not have permission to use this command.

  rankup:
    description: Rank up to the next level if conditions are met.
    usage: /rankup
    permission: bmessentials.rankup.use
    permission-message: You do not have permission to perform this command.

  commandqueue:
    description: Runs the command queue
    usage: /commandqueue run <player/console> <delay>

  version:
    description: Check what chunk version you are in.
    usage: /version

  bmrestart:
    description: Restart the server with a specified timer.
    usage: /bmrestart <30|15|5|1>

  pay:
    description: Pay another player

  bal:
    description: Show your balance

  money:
    description: Show your balance

  balance:
    description: Show your balance

  baltop:
    description: Show top balances

  moneytop:
    description: Show top balances

  eco:
    description: OP economy commands

  help:
    description: Shows help for BMEssentials.
    usage: /help

  commands:
    description: Shows text commands for BMEssentials.
    usage: /commands

  book:
    description: Opens a help book.
    usage: /book <book name>

  text:
    description: Displays command information.
    usage: /text <text name>

  ranks:
    description: Displays rank information.
    usage: /ranks <text name>

  donorranks:
    description: Displays command information.
    usage: /donorranks <text name>

  afk:
    description: Toggle your AFK status.

  chestsort:
    description: Changes ChestSort Settings.

  besttool:
    description: Changes BestTools Settings.

  autoadd:
    description: Changes Drop2Inventory Settings.

  invsee:
    description: View and edit another player's inventory.
    usage: /invsee <player>
    permission: bmessentials.invsee.use

  seen:
    description: Shows when a player was last online.
    usage: /seen <player>

  bms:
    description: Manage Block Miner shops.
    usage: /bms <buy [shop]|disband|invite|remove|transfer|extend|rename|tp|admin>
  imagemap:
    description: Render an image to one or more maps.
    usage: /imagemap <filename> [width] [height]


permissions:
  bmessentials.vot.use:
    description: Allows the player to use the /vot command to start and participate in votes.
    default: true

  bmessentials.vot.reset:
     description: Allows the player to reset or finalize an ongoing vote using /vot reset.
     default: op

  bmessentials.vot.bypasscooldown:
     description: Allows the player to bypass the vote initiation cooldown.
     default: op

  bmessentials.rankup.use:
    description: Allows the user to attempt to rank up.
    default: true

  bmessentials.eco.admin:
    description: Access to all economy admin commands
    default: op

  bmessentials.invsee.use:
    description: Allows the player to open other players' inventories.
    default: op

  bmessentials.shops.color:
    description: Allows the player chose any Legacy color for their shops name on the shops sign.
    default: false

  bmessentials.shops.hex:
    description: Allows the player chose any Hex color for their shops name on the shops sign.
    default: false

  bmessentials.wild.admin:
    description: Allows use of /wild admin commands.
    default: op