name: BMEssentials
version: 2.0
api-version: '1.20'
main: at.sleazlee.bmessentials.BMEssentials
author: SleazLee
description: One plugin to rule them all!
folia-supported: true

softdepend: [HuskHomes, HuskTowns, Vault]

commands:
  bme:
    description: Reloads the BMEssentials plugin.
    usage: /bme

  tpshop:
    description: Sends the player to a shop of their choosing.
    usage: /tpshop <###>

  wild:
    description: Teleports the player to a random server with a random world.
    usage: /wild

  rtp:
    description: Teleports the player to a random server with a random world.
    usage: /rtp

  randomtp:
    description: Teleports the player to a random server with a random world.
    usage: /randomtp

  randomteleport:
    description: Teleports the player to a random server with a random world.
    usage: /randomteleport

  firstjoinmessage:
    description: Sends repeating action bar messages to the player.
    usage: /firstjoinmessage

  trash:
    description: Opens a trash chest.
    usage: /trash
    aliases:
      - disposal

  craft:
    description: Open crafting table GUI
    usage: /craft
    permission: bm.containers.craft
    aliases:
      - crafting
      - craftingtable
      - workbench

  enderchest:
    description: Open a player enderchest GUI
    usage: /enderchest
    permission: bm.containers.enderchest
    aliases:
      - ec
      - echest

  cartography:
    description: Opens a cartography GUI
    usage: /cartography
    permission: bm.containers.cartography
    aliases:
      - cartographytable

  loom:
    description: Opens a loom GUI
    usage: /loom
    permission: bm.containers.loom

  stonecutter:
    description: Opens a stonecutter GUI
    usage: /stonecutter
    permission: bm.containers.stonecutter

  smithing:
    description: Opens a smithing GUI
    usage: /smithing
    permission: bm.containers.smithing
    aliases:
      - smithingtable
      - smith

  grindstone:
    description: Opens a grindstone GUI
    usage: /grindstone
    permission: bm.containers.grindstone
    aliases:
      - grstone
      - gstone

  anvil:
    description: Opens a anvil GUI
    usage: /anvil
    permission: bm.containers.anvil
    aliases:
      - openanvil
      - anv

  bungeetell:
    description: Sends a message to all players on the network.
    usage: /bungeetell

  adminvote:
    description: Sends a testvote to the player given.
    usage: /adminvote <player>

  map:
    description: Sends the player a link to the server map.
    usage: /map

  maps:
    description: Sends the player a link to the server map.
    usage: /maps

  springsheal:
    description: Heals the player.
    usage: /springsheal

  playtime:
    description: Shows the player their current Playtime.
    usage: /playtime

  lag:
    description: Displays general performance info.
    usage: /lag

  bmdiscord:
    description: Gives the player a discord link.
    usage: /bmdiscord

  vot:
    description: Shows Spawn Only Vot message.
    usage: /vot

  voting:
    description: Shows Spawn Only Vot message.
    usage: /voting

  mcmmoboost:
    description: gives a mcmmo boost to a player.
    usage: /mcmmobonus <player>

  diamondcatch:
    description: gives a random ammount of diamonds to a player.
    usage: /diamondcatch <player>

  autoban:
    description: Bans the player for hacking.
    usage: /autoban <player>

  unmute:
    description: Unmutes a player.
    usage: /unmute <player>

  donation:
    description: Give a selected player the selected donation package.
    usage: /donation <player> <package>

  trophyroom:
    aliases: [trophies, trophy]
    description: Opens a players Trophy Room.
    usage: /trophyroom <player>